<?php defined('SYSPATH') OR die('No direct access allowed.');
/**
 * Welcome homepage
 *
 * @package    Core
 * @author     Kohana Team
 * @copyright  (c) 2007-2008 Kohana Team
 * @license    http://kohanaphp.com/license.html
 */
class Welcome_Controller extends Main_Controller {

	public function index()
	{
		$this->template->content = new View('welcome');
		
		$this->user_id = $this->login();

		$this->template->title = 'Welcome';
	}
	
	public function test($do=NULL)
	{
		$this->template->content = new View('welcome');
		
		$this->template->title = 'Welcome';
		
		switch($do){
			case 'add_sms':
				Message_Model::add_message('1112223333','This is a test message '.rand(1,1000));
				break;
			default:
				die('Do Required');
		}
		
		Debug_Toolbar::render(TRUE);
	}
	
	public function login()
	{
		
		// TODO: Build out login functionality
		
		$this->auth = new Auth();
		$this->auth->force_login('admin');
		
		return $this->auth->get_user()->id;
	}

	public function __call($method, $arguments)
	{
		// Disable auto-rendering
		$this->auto_render = FALSE;

		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo 'This text is generated by __call. If you expected the welcome page, you need to use: welcome/index/'.substr(Router::$current_uri, 8);
	}

} // End Welcome Controller